[tool.black]
line-length = 88
target-version = ['py311']
exclude = '''
(
    /terraform/
  | \.venv/
  | \.venv_pack/
  | api_lambda_build/
  | terraform/api_lambda\.zip
  | lambda\.zip
  | /visualization/.*\.png
)
'''
