name: CI / CD

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # ---- Python lint + (optional) tests ----
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - run: pip install black flake8 pytest boto3
      - run: black --check .
      - run: flake8 .

      # run tests if any; ignore absence
      - run: pytest -q || echo "pytest: no tests found"

      # ---- Terraform format, validate, apply ----
      - uses: hashicorp/setup-terraform@v2

      - run: terraform -chdir=terraform init
      - run: terraform -chdir=terraform fmt -check
      - run: terraform -chdir=terraform validate

      - run: terraform -chdir=terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION:    us-east-1
