name: CI / CD

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣  Checkout
    - uses: actions/checkout@v4

    # 2️⃣  Python setup, lint, tests
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - run: pip install black flake8 pytest boto3

    # run Black but skip the nested duplicate directory
    - run: black --check data-pipeline-project

    - run: flake8 .

    - name: Run tests
      run: |
        pytest -q || echo "pytest: no tests found"

    # 3️⃣  Terraform
    - uses: hashicorp/setup-terraform@v2

    - run: terraform -chdir=terraform init
    - run: terraform -chdir=terraform fmt -check
    - run: terraform -chdir=terraform validate

    - name: Terraform Apply
      run: terraform -chdir=terraform apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION:    us-east-1
