# .github/workflows/deploy.yml
name: CI / CD

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read
  id-token: write   # for possible future OIDC use

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Python and cache pip
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}

      - name: Install Python dev/test dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          # It’s better to separate runtime vs dev dependencies:
          # e.g. requirements.txt for runtime (fastapi, mangum, pydantic), 
          # requirements-dev.txt for lint/test (pytest, moto, black, flake8, etc.)
          # Here install dev deps for lint/tests:
          pip install black flake8 pytest pytest-cov moto fastapi[all] mangum boto3 pydantic

      # 3️⃣ Lint: Black & Flake8 on source folders
      - name: Black check
        run: |
          source .venv/bin/activate
          black --check lambda_function api data_feed tests || \
            (echo "Black formatting issues in source folders. Run 'black lambda_function api data_feed tests' locally."; exit 1)

      - name: Flake8 lint
        run: |
          source .venv/bin/activate
          flake8 lambda_function api || \
            (echo "Flake8 issues in source folders."; exit 1)

      # 4️⃣ Run unit tests (with moto mocking DynamoDB/S3)
      # - name: Run pytest
      #   env:
      #     AWS_REGION: us-east-1
      #   run: |
      #     source .venv/bin/activate
      #     pytest --cov=. -q

      # 5️⃣ Configure AWS credentials (for Terraform & smoke tests)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 6️⃣ Build API Lambda package **before** Terraform plan
      - name: Build API Lambda package
        run: |
          python -m venv .venv_pack
          source .venv_pack/bin/activate
          pip install --upgrade pip
          # Install only runtime dependencies for API Lambda (keep minimal to avoid large ZIP):
          # If you have a separate runtime requirements file, use it. Otherwise:
          pip install --target api_lambda_build/python fastapi mangum pydantic
          # Copy API code
          rm -rf api_lambda_build
          mkdir -p api_lambda_build/python
          # Note: if your code imports other modules, ensure they are in api/ or installed above.
          cp -r api api_lambda_build/
          # Zip into terraform folder so Terraform can pick it up:
          cd api_lambda_build && zip -r ../terraform/api_lambda.zip .
          cd ..
        # Make sure api_lambda_build/ and terraform/api_lambda.zip are in .gitignore

      # 7️⃣ Cache Terraform plugins
      - name: Cache Terraform plugins
        uses: actions/cache@v3
        with:
          path: |
            ~/.terraform.d/plugin-cache
          key: ${{ runner.os }}-terraform-${{ hashFiles('terraform/**/*.tf*') }}

      - name: Setup Terraform plugin cache dir
        run: |
          mkdir -p ~/.terraform.d
          cat <<EOF > ~/.terraform.d/cli.hcl
          plugin_cache_dir = "$HOME/.terraform.d/plugin-cache"
          EOF

      # 8️⃣ Setup Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"

      # 9️⃣ Terraform Init (with backend)
      - name: Terraform Init
        working-directory: terraform
        run: terraform init -reconfigure

      # 🔟 Terraform Fmt Check and Validate
      - name: Terraform Fmt Check
        working-directory: terraform
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      # 1️⃣1️⃣ Terraform Plan (now sees correct api_lambda.zip)
      - name: Terraform Plan
        id: tfplan
        working-directory: terraform
        run: |
          terraform plan -out=tfplan.binary \
            -var="alert_topic_arn=${{ secrets.TF_VAR_alert_TOPIC_ARN }}"

      # 1️⃣2️⃣ Comment Terraform Plan on PR
      - name: Comment Terraform Plan on PR
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: terraform/tfplan.binary

      # 1️⃣3️⃣ Terraform Apply only on push to main
      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        working-directory: terraform
        run: terraform apply -auto-approve tfplan.binary

      # 1️⃣4️⃣ Smoke test API endpoint (only after Apply on main)
      - name: Smoke test API endpoint (verbose)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        working-directory: terraform
        env:
          AWS_REGION: us-east-1
        run: |
          set -euo pipefail
          # Turn off xtrace so wrapper prints don't pollute captures:
          set +x
          # Capture raw output (including any wrapper debug lines):
          RAW_OUTPUT=$(terraform output -raw api_endpoint 2>&1)
          # Extract the real HTTPS URL:
          ENDPOINT=$(printf "%s\n" "$RAW_OUTPUT" | grep -Eo 'https://[^[:space:]]+' | head -n1)
          # Re-enable xtrace if you want command logging:
          set -x
          echo "Captured raw terraform output:"
          echo "$RAW_OUTPUT"
          echo "Using extracted endpoint: $ENDPOINT"
          if [ -z "$ENDPOINT" ]; then
            echo "ERROR: api_endpoint output is empty or not found"; exit 1;
          fi
          # Build test URL:
          URL="${ENDPOINT%/}/records?site_id=test-site"
          echo "Calling URL: $URL"
          # Perform request, capture status and body:
          HTTP_STATUS=$(curl -s -o response_body.txt -w "%{http_code}" "$URL")
          echo "HTTP status: $HTTP_STATUS"
          echo "Response body:"
          cat response_body.txt || true
          if [ "$HTTP_STATUS" != "200" ]; then
            echo "Smoke test failed: expected 200 but got $HTTP_STATUS"; exit 1;
          fi
          # Optionally verify valid JSON:
          if command -v jq >/dev/null 2>&1; then
            if ! jq empty response_body.txt; then
              echo "Response is not valid JSON"; exit 1;
            fi
          fi
