# .github/workflows/deploy.yml
name: CI / CD

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read
  id-token: write   # for possible future OIDC use

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Python 3.11 and cache pip
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}

      # 3️⃣ Install runtime + dev dependencies
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          # Install runtime requirements
          pip install -r requirements.txt
          # Install dev/test requirements
          pip install -r requirements-dev.txt

      # 4️⃣ Lint: Black & Flake8 on source folders
      - name: Black check
        run: |
          source .venv/bin/activate
          black --check lambda_function api data_feed tests || \
            (echo "Black formatting issues. Run 'black lambda_function api data_feed tests' locally."; exit 1)

      - name: Flake8 lint
        run: |
          source .venv/bin/activate
          flake8 lambda_function api || \
            (echo "Flake8 issues in source folders."; exit 1)

      # 5️⃣ Run unit tests
      - name: Run pytest
        env:
          AWS_REGION: us-east-1
          AWS_DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: dummy
          AWS_SECRET_ACCESS_KEY: dummy
        run: |
          source .venv/bin/activate
          pytest --maxfail=1 --disable-warnings -q

      # 6️⃣ Configure AWS credentials (for Terraform & smoke tests)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 7️⃣ Build API Lambda package **before** Terraform plan
      - name: Build API Lambda package
        run: |
          python -m venv .venv_pack
          source .venv_pack/bin/activate
          pip install --upgrade pip
          # Install runtime dependencies directly into the function package root:
          rm -rf api_lambda_build
          mkdir -p api_lambda_build
          pip install --target api_lambda_build fastapi mangum pydantic
          # Copy API source code into the same folder
          cp -r api api_lambda_build/
          # Create ZIP from the contents of api_lambda_build (root-level)
          cd api_lambda_build && zip -r ../terraform/api_lambda.zip .
          cd ..
        # Ensure api_lambda_build/ and terraform/api_lambda.zip are in .gitignore

      # 8️⃣ Cache Terraform plugins
      - name: Cache Terraform plugins
        uses: actions/cache@v3
        with:
          path: |
            ~/.terraform.d/plugin-cache
          key: ${{ runner.os }}-terraform-${{ hashFiles('terraform/**/*.tf*') }}

      - name: Setup Terraform plugin cache dir
        run: |
          mkdir -p ~/.terraform.d
          cat <<EOF > ~/.terraform.d/cli.hcl
          plugin_cache_dir = "$HOME/.terraform.d/plugin-cache"
          EOF

      # 9️⃣ Setup Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"

      # 🔟 Terraform Init (with backend)
      - name: Terraform Init
        working-directory: terraform
        run: terraform init -reconfigure

      # 1️⃣1️⃣ Terraform Fmt Check and Validate
      - name: Terraform Fmt Check
        working-directory: terraform
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      # 1️⃣2️⃣ Terraform Plan
      - name: Terraform Plan
        id: tfplan
        working-directory: terraform
        run: |
          terraform plan -out=tfplan.binary \
            -var="alert_topic_arn=${{ secrets.TF_VAR_alert_TOPIC_ARN }}"

      # 1️⃣3️⃣ Comment Terraform Plan on PR
      - name: Comment Terraform Plan on PR
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: terraform/tfplan.binary

      # 1️⃣4️⃣ Terraform Apply only on push to main
      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        working-directory: terraform
        run: terraform apply -auto-approve tfplan.binary

      # 1️⃣5️⃣ Smoke test API endpoint (only after Apply on main)
      - name: Smoke test API endpoint (verbose)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        working-directory: terraform
        env:
          AWS_REGION: us-east-1
        run: |
          set -euo pipefail
          set +x
          RAW_OUTPUT=$(terraform output -raw api_endpoint 2>&1)
          ENDPOINT=$(printf "%s\n" "$RAW_OUTPUT" | grep -Eo 'https://[^: ]+' | head -n1)
          set -x
          echo "Using endpoint: $ENDPOINT"
          if [ -z "$ENDPOINT" ]; then
            echo "ERROR: api_endpoint output empty"; exit 1;
          fi
          sleep 5
          URL="${ENDPOINT%/}/records?site_id=test-site"
          echo "Calling URL: $URL"
          HTTP_STATUS=$(curl -s -o response_body.txt -w "%{http_code}" "$URL")
          echo "HTTP status: $HTTP_STATUS"
          echo "Response body:"; cat response_body.txt || true
          if [ "$HTTP_STATUS" != "200" ]; then
            echo "Smoke test failed: expected 200 but got $HTTP_STATUS"; exit 1;
          fi
          if command -v jq >/dev/null 2>&1; then
            if ! jq empty response_body.txt; then
              echo "Response is not valid JSON"; exit 1;
            fi
          fi
